version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: qbittorrent_server_1
      APP_PORT: 8080
      PROXY_AUTH_ADD: "false"

  server:
    image: hotio/qbittorrent:release-4.6.3@sha256:cc4b6bf253bda4125ef255e2da35a6b02677ca60bc96e460361a6c51d5628469
    environment:
      - PUID=1000
      - PGID=1000
      # - UMASK=002
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
    restart: on-failure