version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: gitea_server_1
      APP_PORT: 8085
      PROXY_AUTH_ADD: "false"

  server:
    image: gitea/gitea:1.21.5-rootless@sha256:ad0c0ed72ddf7cc56b45b32178a0c0e8b6527ca0083f9e5288d93829c5702508
    user: "1000:1000"
    restart: on-failure
    ports:
      - "${APP_GITEA_SSH_PORT}:${APP_GITEA_SSH_PORT}"
    volumes:
      - ${APP_DATA_DIR}/data/gitea/data:/var/lib/gitea
      - ${APP_DATA_DIR}/data/gitea/config:/etc/gitea
    environment:
      GITEA__security__INSTALL_LOCK: "true"
      GITEA__server__DOMAIN: "${APP_DOMAIN}"
      GITEA__server__HTTP_PORT: 8085
      GITEA__server__SSH_DOMAIN: "${APP_DOMAIN}"
      GITEA__server__SSH_PORT: "${APP_GITEA_SSH_PORT}"
      GITEA__server__SSH_LISTEN_PORT: "${APP_GITEA_SSH_PORT}"
      GITEA__server__START_SSH_SERVER: "true"
      GITEA__database__DB_TYPE: "mysql"
      GITEA__database__HOST: "gitea_db_1:3306"
      GITEA__database__NAME: "gitea"
      GITEA__database__USER: "gitea"
      GITEA__database__PASSWD: "moneyprintergobrrr"

  db:
    image: mariadb:11.2.2@sha256:ac933f87a5fc8b743a3c522179116ee63aec31105795dc28dea8b80bb74cdd36
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "gitea"
      MYSQL_USER: "gitea"
      MYSQL_PASSWORD: "moneyprintergobrrr"
      MYSQL_DATABASE: "gitea"
